### PR TITLE
waitAny(Catch): clarify non-empty input list requirement

### LINKED ISSUE #130: Missing documentation: `waitAny []` throws `BlockedIndefinitelyOnSTM`
The documentation for the `waitAny*` functions should mention that passing an empty list will make it throw a `BlockedIndefinitelyOnSTM` exception.

If we agree that this is an issue, I would be happy to open a PR that improves the docs in this regard.

### PR DESCRIPTION
**Pull request by runeksvendsen**
I have only documented the "non-empty list"-requirement in the docs for `waitAny` and `waitAnyCatch`. I have refrained from adding it to the docs for `waitAnyCancel`, `waitAnyCatchCancel`, `waitAnySTM`, and `waitAnyCatchSTM` since the docs for these functions refer to either `waitAny` or `waitAnyCatch`.

Closes #130

### CODE REVIEW

File: Control/Concurrent/Async.hs [hunk 1]
```diff
@@ -478,6 +479,7 @@ waitAnyCatch = atomically . waitAnyCatchSTM
 --
 -- @since 2.1.0
 waitAnyCatchSTM :: [Async a] -> STM (Async a, Either SomeException a)
+waitAnyCatchSTM [] = error "waitAnyCatchSTM: invalid argument: input list must be non-empty"
```
Comment (simonmar) [inline Control/Concurrent/Async.hs:482]: 1. please throw an exception, don't use `error`
2. keep lines under 80 columns

Comment (runeksvendsen) [reply Control/Concurrent/Async.hs:482]: > 1. please throw an exception, don't use `error`

In the associated issue you said using `ErrorCall` is fine. And calling `error` is the same as throwing `ErrorCall` according to https://www.stackage.org/haddock/lts-19.5/base-4.15.1.0/Control-Exception.html#t:ErrorCall. What am I missing?

Comment (simonmar) [reply Control/Concurrent/Async.hs:482]: `error` is not the same as `throwIO`: https://hackage.haskell.org/package/base-4.16.1.0/docs/Control-Exception.html#v:throwIO
